spring:
  application:
    name: turbin
    
server:
  port: 5001
  rabbitmq:
    host: 192.168.200.131
    port: 15672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
turbine:
  app-config: order-service, zuul
  cluster-name-expression: new String("default")
